### Register
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username":"MANAGER",
    "password": "MGR",
    "tipeUser": "MANAGER",
    "akses": {
        "bookingGym": true,
        "bookingKelas": true,
        "jadwalGym": true,
        "jadwalInstruktur": true,
        "profilUser": true,
        "daftarUser": true
    }
}

### Login
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username":"MANAGER",
    "password": "MGR"
}

### Get All User
POST http://localhost:5000/users
Content-Type: application/json

{
    "_id": 1,
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjgwNzU5Njc5LCJleHAiOjE2ODIwNTU2Nzl9.rc4ULj1c6BllMqg4pOzhUvbavIQdf5n7b3wF0w7Wli8"
}

### Get User By Id
POST http://localhost:5000/findUser/1
Content-Type: application/json

{
    "_id": 1,
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjgwNzU5Njc5LCJleHAiOjE2ODIwNTU2Nzl9.rc4ULj1c6BllMqg4pOzhUvbavIQdf5n7b3wF0w7Wli8"
}

### Update User 
POST http://localhost:5000/users/1
Content-Type: application/json

{
    "akses": {
      "daftarUser": true
    },
    "_id": 1,
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjgwNzU5Njc5LCJleHAiOjE2ODIwNTU2Nzl9.rc4ULj1c6BllMqg4pOzhUvbavIQdf5n7b3wF0w7Wli8"
}

### Aktivasi User 
POST http://localhost:5000/aktivasiUser/4
Content-Type: application/json

{
    "aktivasi": true,
    "_id": 1,
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjgwNzU5Njc5LCJleHAiOjE2ODIwNTU2Nzl9.rc4ULj1c6BllMqg4pOzhUvbavIQdf5n7b3wF0w7Wli8"
}

### Update Deposit User 
POST http://localhost:5000/updateDepositUser/4
Content-Type: application/json

{
    "deposit": 10000,
    "_id": 1,
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjgwNzU5Njc5LCJleHAiOjE2ODIwNTU2Nzl9.rc4ULj1c6BllMqg4pOzhUvbavIQdf5n7b3wF0w7Wli8"
}

### Update User Then Login
POST http://localhost:5000/updateUserThenLogin/1
Content-Type: application/json

{
    "_id": 1,
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjc3MDQ4NDM0LCJleHAiOjE2NzgzNDQ0MzR9.p_KA5GF7BsROTWIP62gP-uh8u0mLB8emlwf2w72LHuc"
}

### Get User By Username
POST http://localhost:5000/getUsername
Content-Type: application/json

{
    "username": "MANAGER",
    "_id": 1,
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjgwNzU5Njc5LCJleHAiOjE2ODIwNTU2Nzl9.rc4ULj1c6BllMqg4pOzhUvbavIQdf5n7b3wF0w7Wli8"
}

### Get All Jadwal Instruktur
POST http://localhost:5000/jadwalInstrukturs
Content-Type: application/json

{
    "_id": 1,
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjgwNzU5Njc5LCJleHAiOjE2ODIwNTU2Nzl9.rc4ULj1c6BllMqg4pOzhUvbavIQdf5n7b3wF0w7Wli8"
}

### Get Jadwal Instruktur By Id
POST http://localhost:5000/jadwalInstrukturs/1
Content-Type: application/json

{
    "_id": 1,
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjgwNzU5Njc5LCJleHAiOjE2ODIwNTU2Nzl9.rc4ULj1c6BllMqg4pOzhUvbavIQdf5n7b3wF0w7Wli8"
}

### Save Jadwal Instruktur 
POST http://localhost:5000/saveJadwalInstruktur
Content-Type: application/json

{
    "namaKelas": "zumba",
    "dariJam": "10.00",
    "sampaiJam": "11.00",
    "tanggal": "2023-03-05",
    "userId": 2,
    "_id": 1,
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjgwNzU5Njc5LCJleHAiOjE2ODIwNTU2Nzl9.rc4ULj1c6BllMqg4pOzhUvbavIQdf5n7b3wF0w7Wli8"
}

### Get All Jadwal Gym 
POST http://localhost:5000/jadwalGyms
Content-Type: application/json

{
    "_id": 1,
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjgwNzU5Njc5LCJleHAiOjE2ODIwNTU2Nzl9.rc4ULj1c6BllMqg4pOzhUvbavIQdf5n7b3wF0w7Wli8"
}

### Get Jadwal Gym By Id
POST http://localhost:5000/jadwalGyms/1
Content-Type: application/json

{
    "_id": 1,
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjgwNzU5Njc5LCJleHAiOjE2ODIwNTU2Nzl9.rc4ULj1c6BllMqg4pOzhUvbavIQdf5n7b3wF0w7Wli8"
}

### Save Jadwal Gym
POST http://localhost:5000/saveJadwalGym
Content-Type: application/json

{
    "dariJam": "10.00",
    "sampaiJam": "11.00",
    "tanggal": "2023-03-05",
    "jumlahMember": 2,
    "_id": 1,
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjgwNzU5Njc5LCJleHAiOjE2ODIwNTU2Nzl9.rc4ULj1c6BllMqg4pOzhUvbavIQdf5n7b3wF0w7Wli8"
}

### Get All Booking Gym 
POST http://localhost:5000/bookingGyms
Content-Type: application/json

{
    "_id": 1,
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjgwNzU5Njc5LCJleHAiOjE2ODIwNTU2Nzl9.rc4ULj1c6BllMqg4pOzhUvbavIQdf5n7b3wF0w7Wli8"
}

### Get Booking Gym By Id
POST http://localhost:5000/bookingGyms/1
Content-Type: application/json

{
    "_id": 1,
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjgwNzU5Njc5LCJleHAiOjE2ODIwNTU2Nzl9.rc4ULj1c6BllMqg4pOzhUvbavIQdf5n7b3wF0w7Wli8"
}

### Save Booking Gym 
POST http://localhost:5000/saveBookingGym
Content-Type: application/json

{
    "userId": 5,
    "jadwalGymId": 4,
    "_id": 5,
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNjc5ODc2NTMyLCJleHAiOjE2ODExNzI1MzJ9.RfxuLYk2VIxlxr_ai0xCiF0nTayfhoafcQnnSMf-yy0"
}

### Get All Booking Kelas
POST http://localhost:5000/bookingKelas
Content-Type: application/json

{
    "_id": 1,
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjgwNzU5Njc5LCJleHAiOjE2ODIwNTU2Nzl9.rc4ULj1c6BllMqg4pOzhUvbavIQdf5n7b3wF0w7Wli8"
}

### Get Booking Kelas By Id
POST http://localhost:5000/bookingKelas/1
Content-Type: application/json

{
    "_id": 1,
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjgwNzU5Njc5LCJleHAiOjE2ODIwNTU2Nzl9.rc4ULj1c6BllMqg4pOzhUvbavIQdf5n7b3wF0w7Wli8"
}

### Save Booking Kelas
POST http://localhost:5000/saveBookingKelas
Content-Type: application/json

{
    "userId": 5,
    "jadwalInstrukturId": 3,
    "_id": 5,
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNjc5ODc2NTMyLCJleHAiOjE2ODExNzI1MzJ9.RfxuLYk2VIxlxr_ai0xCiF0nTayfhoafcQnnSMf-yy0"
}